server:
  address: 127.0.0.1
  port: 10001

spring:
  application:
    name: eureka-rest

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
